spring:
  application:
    name: petNote
  profiles:
    active: privacy
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

#  data:
#    redis:
#      host: localhost
#      port: 6379
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.petnote
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    jdbc-type-for-null: 'NULL'
    call-setters-on-nulls: true
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
logging:
  level:
    org.springframework.security: DEBUG
    com.zaxxer.hikari: INFO
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis.spring.SqlSessionFactoryBean: INFO
    jdbc.resultset: OFF
    com.p6spy: INFO
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
app:
  jwt:
    issuer: petNote
    access-exp-minutes: 15
    refresh-exp-days: 14
    secret: "aZbK93jf39Jf02FslkFja3021hfjs93Kd8sfl3kfj9w9s2dkj3"
server:
  port: 9090